import pandas as pd
data=pd.read_csv(r"C:\Users\Asus\OneDrive\Desktop\Data_Science\salaries.csv")
df=pd.DataFrame(data)
h=df.head()
print(h)
a=df.shape
print(a)
b=df.query('salary>900000')
print(b)
c=df.sort_values('job_title')
print(c)
d=df.query('job_title=="AI Engineer"')
print(d)
e=(df['job_title']=="AI Engineer").sum()
print(e)
f=df.describe()
print(f)
'''g=df.info()
print(g)'''
h=df.query('company_location=="IN"')
print(h)
i=df.groupby('company_location')
print(i)
j=df['salary'].describe()
print(max)
k=df['salary'].max()
print('max of salary is:',k)
l=df['salary'].min()
print('min of salary is:',l)
m=df['salary'].var()
print('variance of salary is:',m)
n=df['salary'].std()
print('std of salary is:',n)
o=df['salary'].mean()
print('mean of salary is:',o)
p=df['salary'].median()
print('median of salary is:',p)
q=df['salary'].mode()
print('mode of salary is:',q)
#to find the null values avalible or not in the data set
r=df.isnull().values.any()
print(r)
#to find the count of null values
s=df.isnull().sum().sum()
print(s)
#to find the null values particularly in the data set as a table
t=df.isnull().sum()
print(t)
u=df.isnull()
print(u)
#to check the rows and columns that contains null values
v=df.isnull().any(axis=1)
print(v)
w=df.isnull().any(axis=0)
print(w)